### ISSUE TITLE
Swift Package Manager Support and SwiftUI Support?

### ISSUE THREAD

**Issue by JamesCastrejon** [cocoatoucher/Glide#7]
Any thoughts on supporting SPM and/or SwiftUI?

**Comment by cocoatoucher** [comment]
Hello, spm is already supported
No plans yet on the SwiftUI support on the UI parts, rest is mostly SpriteKit anyway

**Comment by JamesCastrejon** [comment]
Oh, okay then, sounds good. Thanks for letting me know!
